call_server/call/models.py
import hashlib
from datetime import datetime

from ..extensions import db

from .constants import STRING_LEN


class Call(db.Model):
    # tracks outbound calls to target
    __tablename__ = 'calls'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime(timezone=True))

    # session
    session_id = db.Column(db.ForeignKey('calls_session.id'))
    session = db.relationship('Session', backref=db.backref('calls'))

    # campaign
    campaign_id = db.Column(db.ForeignKey('campaign_campaign.id'))
    campaign = db.relationship('Campaign')

    # target
    target_id = db.Column(db.ForeignKey('campaign_target.id'))
    target = db.relationship('Target')

    # twilio attributes
    call_id = db.Column(db.String(40))    # twilio call ID
    status = db.Column(db.String(25))     # twilio call status
    duration = db.Column(db.Integer)      # twilio call time in seconds

    def __init__(self, session_id, campaign_id, target_id, call_id=None, status='unknown', duration=0):
        self.timestamp = datetime.utcnow()
        self.session_id = session_id
        self.campaign_id = campaign_id
        self.target_id = target_id
        self.call_id = call_id
        self.status = status
        self.duration = duration

    def __repr__(self):
        return u'<Call to {}>'.format(self.target.name)

    def target_display(self):
        if self.target:
            return self.target.full_name()


class Session(db.Model):
    # tracks calls session by user for a campaign
    __tablename__ = 'calls_session'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime(timezone=True))

    # campaign
    campaign_id = db.Column(db.ForeignKey('campaign_campaign.id'))
    campaign = db.relationship('Campaign')

    # user attributes
    phone_hash = db.Column(db.String(64), nullable=True)  # hashed phone number (optional)
    location = db.Column(db.String(STRING_LEN))  # provided location

    # twilio attributes
    from_number = db.Column(db.String(16))  # campaign call number, e164
    twilio_id = db.Column(db.String(40))    # twilio call ID
    duration = db.Column(db.Integer)        # twilio call time in seconds
    status = db.Column(db.String(25))       # session status (initiated, completed, failed)

    direction = db.Column(db.String(25))    # (inbound, outbound)
    queue_delay = db.Column(db.Interval)  # difference between timestamp and ringing event

    @classmethod
    def hash_phone(cls, number):
        """
        Takes a phone number and returns a 64 character string
        """
        return hashlib.sha256(number).hexdigest()

    def __init__(self, campaign_id, phone_number=None, location=None, from_number=None, status='initiated', direction='outbound'):
        self.timestamp = datetime.utcnow()
        self.campaign_id = campaign_id
        if phone_number:
            self.phone_hash = self.hash_phone(phone_number)
        self.location = location
        self.from_number = from_number
        self.status = status
        self.direction = direction

    def __repr__(self):
        return u'<Session for {}>'.format(self.phone_hash)

call_server/user/models.py
from datetime import datetime

from sqlalchemy_utils.types import phone_number
from werkzeug import generate_password_hash, check_password_hash
from flask_login import UserMixin

from ..extensions import db
from sqlalchemy import func
from .constants import (USER_ROLE, USER_ADMIN, USER_STAFF,
                        USER_STATUS, USER_ACTIVE,
                        STRING_LEN, PASSWORD_LEN_MAX)


class User(db.Model, UserMixin):
    __tablename__ = 'user_user'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(STRING_LEN), nullable=False, unique=True)
    email = db.Column(db.String(STRING_LEN), nullable=False, unique=True)
    openid = db.Column(db.String(STRING_LEN), unique=True)
    activation_key = db.Column(db.String(STRING_LEN))
    created_time = db.Column(db.DateTime, default=datetime.utcnow)
    last_accessed = db.Column(db.DateTime)

    phone = db.Column(phone_number.PhoneNumberType())

    _password = db.Column('password', db.String(PASSWORD_LEN_MAX), nullable=False)

    def __unicode__(self):
        return self.name

    def _get_password(self):
        return self._password

    def _set_password(self, password):
        self._password = generate_password_hash(password)
    # Hide password encryption by exposing password field only.
    password = db.synonym('_password',
                          descriptor=property(_get_password,
                                              _set_password))

    def check_password(self, password):
        if self.password is None:
            return False
        return check_password_hash(self.password, password)

    # One-to-many relationship between users and roles.
    role_code = db.Column(db.SmallInteger, default=USER_STAFF)

    @property
    def role(self):
        return USER_ROLE[self.role_code]

    def is_admin(self):
        return self.role_code == USER_ADMIN

    # One-to-many relationship between users and user_statuses.
    status_code = db.Column(db.SmallInteger, default=USER_ACTIVE)

    @property
    def status(self):
        return USER_STATUS[self.status_code]

    # ================================================================
    # Class methods

    @classmethod
    def authenticate(cls, login, password):
        user = cls.query.filter(db.or_(
            func.lower(User.name) == func.lower(login),
            func.lower(User.email) == func.lower(login)
        )).first()

        if user:
            authenticated = user.check_password(password)
        else:
            authenticated = False

        return user, authenticated

    @classmethod
    def search(cls, keywords):
        criteria = []
        for keyword in keywords.split():
            keyword = '%' + keyword + '%'
            criteria.append(db.or_(
                User.name.ilike(keyword),
                User.email.ilike(keyword),
            ))
        q = reduce(db.and_, criteria)
        return cls.query.filter(q)

    @classmethod
    def get_by_id(cls, user_id):
        return cls.query.filter_by(id=user_id).first_or_404()

    def check_name(self, name):
        return User.query.filter(db.and_(User.name == name, User.email != self.id)).count() == 0

call_server/campaign/views.py
import datetime

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort, jsonify)
from flask.json import JSONEncoder
from flask_login import login_required
from flask_store.providers.temp import TemporaryStore

import sqlalchemy
from sqlalchemy.sql import func, desc

from twilio.jwt.client import ClientCapabilityToken

from ..extensions import db
from ..political_data import COUNTRY_CHOICES
from ..utils import choice_items, choice_keys, choice_values_flat, duplicate_object

from .constants import EMPTY_CHOICES, STATUS_LIVE
from .models import (Campaign, Target, CampaignTarget,
                     AudioRecording, CampaignAudioRecording,
                     TwilioPhoneNumber)
from ..call.models import Call
from ..schedule.models import ScheduleCall
from .forms import (CountryTypeForm, CampaignForm, CampaignAudioForm,
                    AudioRecordingForm, CampaignLaunchForm,
                    CampaignStatusForm, TargetForm)

campaign = Blueprint('campaign', __name__, url_prefix='/admin/campaign')


@campaign.before_request
@login_required
def before_request():
    # all campaign routes require login
    pass


@campaign.route('/')
def index():
    campaigns = Campaign.query.order_by(desc(Campaign.status_code), desc(Campaign.id)).all()
    calls = (db.session.query(Campaign.id, func.count(Call.id))
            .filter(Call.status == 'completed')
            .join(Call).group_by(Campaign.id))
    return render_template('campaign/list.html',
        campaigns=campaigns, calls=dict(calls.all()))


@campaign.route('/create', methods=['GET', 'POST'])
@campaign.route('/<int:campaign_id>/edit-type', methods=['GET', 'POST'])
def country_type(campaign_id=None):
    edit = False
    if campaign_id:
        edit = True

    if edit:
        campaign = Campaign.query.filter_by(id=campaign_id).first_or_404()
    else:
        campaign = None

    form = CountryTypeForm()
    form.campaign_country.choices = choice_items(COUNTRY_CHOICES)

    # set up a list for all campaign types in each country
    country_type_choices = dict()
    all_valid_choices = list()
    for country_code, country_name in COUNTRY_CHOICES:
        country_type_choices[country_code] = list()
        for campaign_type, type_name in Campaign.get_campaign_type_choices(country_code):
            country_type_choices[country_code].append((campaign_type, type_name))
            all_valid_choices.append((campaign_type, type_name))

    form.campaign_type.choices = choice_items(all_valid_choices)  # accepts all valid choices, but updates dynamically in view

    if form.validate_on_submit():
        country_code = form.campaign_country.data
        campaign_type = form.campaign_type.data
        campaign_language = form.campaign_language.data

        if campaign and country_code and campaign_type:
            campaign.country_code = country_code
            campaign.campaign_type = campaign_type
            campaign.campaign_language = campaign_language
            db.session.add(campaign)
            db.session.commit()
            return redirect(
                url_for('campaign.form', campaign_id=campaign.id)
            )
        elif country_code and campaign_type and campaign_language:
            return redirect(
                url_for('campaign.form',
                    country_code=country_code,
                    campaign_type=campaign_type,
                    campaign_language=campaign_language)
            )

    if edit:
        form.campaign_country.data = campaign.country_code
        form.campaign_type.data = campaign.campaign_type
        form.campaign_language.data = campaign.campaign_language

    return render_template('campaign/country_type.html',
        form=form, country_types=country_type_choices)

@campaign.route('/create/<string(length=2):campaign_language>-<string(length=2):country_code>/<string:campaign_type>', methods=['GET', 'POST'])
@campaign.route('/<int:campaign_id>/edit', methods=['GET', 'POST'])
def form(country_code=None, campaign_type=None, campaign_id=None, campaign_language=None):
    edit = False
    if campaign_id:
        edit = True

    if edit:
        campaign = Campaign.query.filter_by(id=campaign_id).first_or_404()
        campaign_data = campaign.get_campaign_data()
        form = CampaignForm(obj=campaign, campaign_data=campaign_data)
        form.campaign_country.data = campaign_data.country_code
    else:
        campaign = Campaign()
        campaign.country_code = country_code
        campaign.campaign_type = campaign_type
        campaign.campaign_language = campaign_language
        campaign_data = campaign.get_campaign_data()
        form = CampaignForm(campaign_data=campaign_data)
        form.campaign_country.data = country_code
        form.campaign_type.data = campaign_type

    # filter call in numbers on client side
    call_in_map = {}
    for number in TwilioPhoneNumber.available_numbers().filter_by(call_in_allowed=True):
        if campaign.id != number.call_in_campaign.id:
            call_in_map[number.id] = number.call_in_campaign.name
    form.phone_number_set.render_kw = { "data-call_in_map": JSONEncoder().encode(call_in_map) }

    # for fields with dynamic choices, set to empty here in view
    # will be updated in client
    form.target_set.choices = choice_items(EMPTY_CHOICES)

    # set form.show_special based on value of campaign.include_special
    if campaign.include_special:
        form.show_special.data = True

    if form.validate_on_submit():
        # can't use populate_obj with nested forms, iterate over fields manually
        for field in form:
            if field.name not in ['target_set', 'campaign_country', 'campaign_type']:
                setattr(campaign, field.name, field.data)

        # handle target_set nested data
        target_list = []
        for target_data in form.target_set.data:
            # create Target object
            target = Target()
            for (field, val) in target_data.items():
                setattr(target, field, val)
            db.session.add(target)
            target_list.append(target)

            # update or create CampaignTarget membership
            try:
                campaign_target = CampaignTarget.query.filter_by(campaign=campaign, target=target).one()
            except sqlalchemy.orm.exc.NoResultFound:
                # create a new one
                campaign_target = CampaignTarget()
                campaign_target.campaign = campaign
                campaign_target.target = target
            # update order
            campaign_target.order = target_data['order']

            db.session.add(campaign_target)
            db.session.commit()

        # save campaign.target_set
        setattr(campaign, 'target_set', target_list)
        db.session.add(campaign)
        db.session.commit()

        # if allow_call_in, set call_in_allowed on phone_number_set
        if campaign.allow_call_in:
            for n in campaign.phone_number_set:
                n.call_in_allowed = n.set_call_in(campaign)
                db.session.add(n)
            db.session.commit()
        # TODO, allow_call_in on just one number?

        if edit:
            flash('Campaign updated.', 'success')
        else:
            flash('Campaign created.', 'success')

        if form.submit_skip_audio.data:
            return redirect(url_for('campaign.launch', campaign_id=campaign.id))
        else:
            return redirect(url_for('campaign.audio', campaign_id=campaign.id))

    return render_template('campaign/form.html', form=form, edit=edit, campaign_id=campaign_id,
                           descriptions=current_app.config.CAMPAIGN_FIELD_DESCRIPTIONS,
                           campaign_has_audio=campaign.has_audio())



@campaign.route('/<int:campaign_id>/copy', methods=['GET', 'POST'])
def copy(campaign_id):
    orig_campaign = Campaign.query.filter_by(id=campaign_id).first_or_404()
    new_campaign = duplicate_object(orig_campaign)
    new_campaign.name = orig_campaign.name + " (copy)"
    db.session.add(new_campaign)
    db.session.commit()

    # duplicate_object skips sets
    # recreate m2m objects manually
    if orig_campaign.target_set:

        for target in orig_campaign.target_set:
            # update or create CampaignTarget membership
            try:
                campaign_target = CampaignTarget.query.filter_by(campaign=new_campaign, target=target).one()
            except sqlalchemy.orm.exc.NoResultFound:
                # create a new one
                campaign_target = CampaignTarget()
                campaign_target.campaign = new_campaign
                campaign_target.target = target
            db.session.add(campaign_target)
        new_campaign.target_set = orig_campaign.target_set
        db.session.add(new_campaign)
        db.session.commit()

    flash('Campaign copied.', 'success')
    return redirect(url_for('campaign.form', campaign_id=new_campaign.id))


@campaign.route('/<int:campaign_id>/audio', methods=['GET', 'POST'])
def audio(campaign_id):
    campaign = Campaign.query.filter_by(id=campaign_id).first_or_404()
    form = CampaignAudioForm()

    twilio_client = current_app.config.get('TWILIO_CLIENT')
    twilio_capability = ClientCapabilityToken(*twilio_client.auth)
    twilio_capability.allow_client_outgoing(current_app.config.get('TWILIO_PLAYBACK_APP'))

    for field in form:
        campaign_audio, is_default_message = campaign.audio_or_default(field.name)
        if not is_default_message:
            field.data = campaign_audio

    if form.validate_on_submit():
        form.populate_obj(campaign)

        db.session.add(campaign)
        db.session.commit()

        flash('Campaign audio updated.', 'success')
        return redirect(url_for('campaign.launch', campaign_id=campaign.id))

    return render_template('campaign/audio.html', campaign=campaign, form=form,

call_server/templates/campaign/choose_country.html
{% from "macros/_form.html" import render_field, render_label, render_input, render_button with context %}

{% set label_width = 'col-sm-2' %}
{% set control_width = 'col-sm-6' %}
{% macro render_field_default(field, offset='', control_class=control_width, group='') %}
    {%if offset%}{% set control_class = control_width+' '+offset %}{%endif%}
    {{ render_field(field, class_={'label': label_width,
                                   'control': control_class,
                                   'group': group}
                    ) }}
{% endmacro %}


{% set page_title = _("Campaign") %}

{% extends "layouts/base_admin.html" %}

{% block body %}
<h3>New Campaign</h3>

<form class="form-horizontal" id="campaign" method="POST" action="" >
    {{ form.hidden_tag() }}
    <fieldset class="border">
        <legend>Country</legend>

        {{render_field_default(form.country_type)}}
    </fieldset>

    <div class="form-group container">
        <div class="form-actions">
            <div class="pull-right">
                {{render_button(form.submit, {'field':'btn-success', 'icon':'arrow-right'}) }}
            </div>
        </div>
    </div>
</form>
{% endblock %}

call_server/templates/campaign/country_type.html
{% from "macros/_form.html" import render_field, render_label, render_input, render_button with context %}

{% set label_width = 'col-sm-2' %}
{% set control_width = 'col-sm-6' %}
{% macro render_field_default(field, offset='', control_class=control_width, group='') %}
    {%if offset%}{% set control_class = control_width+' '+offset %}{%endif%}
    {{ render_field(field, class_={'label': label_width,
                                   'control': control_class,
                                   'group': group}
                    ) }}
{% endmacro %}


{% set page_title = _("Campaign") %}

{% extends "layouts/base_admin.html" %}

{% block body %}
<h3>New Campaign</h3>

<form class="form-horizontal" id="campaign" method="POST" action="" >
    {{ form.hidden_tag() }}
    <fieldset class="border">
        <legend>Get Started</legend>

        {{render_field_default(form.campaign_country)}}

        {# form tricks to update campaign_type dynamically based on country #}
        {% with %}
        <div class="form-group campaign_type">
            {% set nested_field = form.campaign_type %}
            {{ render_label(nested_field, label_width) }}
            <div class="controls {{control_width}}">
            {{ nested_field(class_='form-control inline', **{'data-nested-choices': country_types|json} ) }}
            {% if nested_field.errors -%}
                {% for error in nested_field.errors -%}
                <span class="help-block error">{{ error|e }}</span>
                {%- endfor %}
            {%- endif %}
            </div>
        </div>
        {% endwith %}

        {{render_field_default(form.campaign_language)}}

    </fieldset>

    <div class="form-group container">
        <div class="form-actions">
            <div class="pull-right">
                {{render_button(form.submit, {'field':'btn-success', 'icon':'arrow-right'}) }}
            </div>
        </div>
    </div>
</form>
{% endblock %}

call_server/templates/campaign/form.html
{% from "macros/_form.html" import render_field, render_label, render_input, render_button with context %}

{% set label_width = 'col-sm-2' %}
{% set control_width = 'col-sm-6' %}
{% macro render_field_default(field, offset='', control_class=control_width, group='') %}
    {%if offset%}{% set control_class = control_width+' '+offset %}{%endif%}
    {{ render_field(field, class_={'label': label_width,
                                   'control': control_class,
                                   'group': group}
                    ) }}
{% endmacro %}


{% set page_title = _("Campaign") %}

{% extends "layouts/base_admin.html" %}

{% block body %}
<h3>{% if edit %}Edit Campaign{%else%}New Campaign{%endif%}</h3>

<form class="form-horizontal" id="campaign" method="POST" action="" >
    {{ form.hidden_tag() }}

    <fieldset class="border">
        <legend>Type</legend>

        {{render_field_default(form.name) }}

        {{render_field_default(form.campaign_country)}}
        {{render_field_default(form.campaign_type)}}

        {% if form.campaign_state.choices %}
            {{render_field_default(form.campaign_state)}}
        {% endif %}

        {% if form.campaign_subtype.choices %}
            {{render_field_default(form.campaign_subtype)}}
        {% endif %}
    </fieldset>

    <fieldset class="border">
        <legend>Targets</legend>
        {{ render_field(form.segment_by, class_={'label': label_width,
                                                 'control': control_width,
                                                 'clear': True}) }}
        {{ render_field(form.locate_by, class_={'label': label_width,
                                                 'control': control_width,
                                                 'clear': True}) }}

        <div class="form-group special_targets">
        <label class="control-label col-sm-2"></label>
            <div class="controls col-sm-6">
                {{ form.show_special(class_ = 'checkbox-inline') }}
                {{ render_label(form.show_special, 'inline') }}
                {% with %}
                {% if form.include_special.data %}
                    {% set include_special_style = '' %}
                {% else %}
                    {% set include_special_style = 'display:none;' %}
                {% endif %}
                <div class="input-group inline" style="{{include_special_style}}">
                    {{ form.include_special() }}
                    {{ render_label(form.include_special, 'inline') }}
                </div>
                <span class="help-block"></span>
                {% endwith %}
            </div>
        </div>

        <div class="form-group hide-initial" id="set-targets">
            {{render_label(form.target_set, label_width)}}
            <div class="controls {{control_width}}">
                <div class="control-group">
                    <div class="input-group col-xs-10 col-sm-12 col-md-10 left" id="target-search">
                        <div class="search-results open">
                            <input type="text" class="form-control" name="target-search" placeholder="search"/>
                        </div>
                        <div class="input-group-btn search-field">
                          <button type="button" class="btn btn-flat btn-white dropdown-toggle" data-toggle="dropdown">Field <span class="caret"></span></button>
                          <ul class="dropdown-menu">
                            <li><a href="#" id="state">State</a></li>
                            <li><a href="#" id="last_name">Name</a></li>
                            <!--<li><a href="#">Committee</a></li>-->
                          </ul>
                           <input type="hidden" name="search_field" />
                        </div>
                        <span class="input-group-btn">
                            <button class="btn btn-default search" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                                <span class="glyphicon glyphicon-repeat spin hide-initial"></span>
                            </button>
                        </span>
                    </div>
                    <div class="input-group col-xs-2 right">
                        <button class="btn btn-primary add" type="button">Add</button>
                        <div class="description">
                            <span class="glyphicon glyphicon-info-sign info small"></span>
                            <span class="help-inline">{{ descriptions.get('target_set')|safe }}</span>
                        </div>
                    </div>
                </div>
                <span class="search-help-block"></span>

                <!-- target_set entries stored as hidden inputs named target_set-N-FIELD -->
                <div id="target-set" class="hidden">
                    {% if form.target_set.data|length %}
                    <input type="hidden" name="target_set_length" value="{{form.target_set|length}}" />
                    {% endif %}

                    {% for error in form.target_set.errors -%}
                    {# load errors here, for client-side display #}
                    <input type="hidden" name="{{error.target}}-error" value="{{ error.message }}" />
                    {%- endfor %}

                    {% for t in form.target_set.data %}
                    <input type="hidden" name="target_set-{{loop.index0}}-order" value="{{loop.index0}}" />
                    <input type="hidden" name="target_set-{{loop.index0}}-title" value="{{t.title}}" />
                    <input type="hidden" name="target_set-{{loop.index0}}-name" value="{{t.name}}" />
                    <input type="hidden" name="target_set-{{loop.index0}}-number" value="{{t.number.international}}" />
                    <input type="hidden" name="target_set-{{loop.index0}}-uid" value="{{t.uid}}" />
                    {% endfor %}
                </div>

                <ol class="target-list list-group sortable hide-initial"></ol>
                <span class="help-block"></span>
            </div>
        </div>

        {{render_field_default(form.target_ordering) }}
        {{render_field_default(form.target_offices) }}
        {{render_field_default(form.call_limit, offset='col-sm-offset-2') }}

        {% with %}
        {% if form.call_maximum.data > 0 %}
            {% set call_max_display = '' %}
        {% else %}
            {% set call_max_display = 'hide-initial' %}
        {% endif %}
        {{render_field_default(form.call_maximum, group=call_max_display) }}
        {% endwith %}
    </fieldset>

    <fieldset class="border">
        <legend>Phone Numbers</legend>
        {{render_field_default(form.phone_number_set) }}
        <div class="col-sm-6 col-sm-offset-2">
            <div class="pull-right"><a class="btn btn-default" href="/admin/system" target="_blank">Get More</a> </div>
        </div>
        {{render_field_default(form.allow_call_in, offset='col-sm-offset-2') }}
        {{render_field_default(form.allow_intl_calls, offset='col-sm-offset-2') }}
        {{render_field_default(form.prompt_schedule, offset='col-sm-offset-2') }}
    </fieldset>

    <div class="form-group container">
        <div class="form-actions">
            <div class="pull-left">
                <a href="{{url_for('campaign.country_type', campaign_id=campaign_id)}}" class="btn btn-warning">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
                </a>
                {% if edit %}
                    <a class="btn btn-warning" href="{{ url_for('campaign.status', campaign_id=campaign_id) }}"><span class="glyphicon glyphicon-edit"></span> Edit Status</a>
                {%endif%}
            </div>
            <div class="pull-right">
                {{render_button(form.submit, {'field':'btn-success', 'icon':'arrow-right'}) }}
                {% if campaign_has_audio %}
                 {{render_button(form.submit_skip_audio, {'field':'btn-primary', 'icon':'check'}) }}
                {% endif %}
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block scripts %}

<script type="text/template" id="search-results-dropdown-tmpl">
    <ul class="dropdown-menu open">
      <li role="presentation" class="dropdown-header">
        Search Results <span class="close btn btn-default btn-xs">&times;</span>
      </li>
    </ul>
</script>

<script type="text/template" id="search-results-item-tmpl">
    <li class="result">
        <a data-object='{ "title":"<%= data.title %>",
                          "name":"<%= data.first_name %> <%= data.last_name %><% if (data.office_name){ %> <%= data.office_name %> office<% } %>",
                          "number":"<%= data.phone %>",
                          "uid": "<%= data.uid %>"
                        }'>
            <span class="text"><%= data.title %> <%= data.first_name %> <%= data.last_name %> <% if (data.office_name){ %>(<%= data.office_name %>)<% } %></span>
            <span class="phone"><%= data.phone %></span>
        </a>
    </li>
</script>

<script type="text/template" id="target-item-tmpl">
    <span data-field="title" contenteditable="plaintext-only" placeholder="Title"><%= data.title %></span>
    <span data-field="name" contenteditable="plaintext-only" placeholder="Name"><%= data.name %></span>
    <span data-field="number" contenteditable="plaintext-only" placeholder="Phone"><%= data.number %></span>

    <div class="pull-right">
        <span class="glyphicon glyphicon-move handle btn btn-xs"></span>
        <span class="glyphicon glyphicon-remove remove btn btn-xs btn-danger"></span>
    </div>
</script>

{% endblock %}

call_server/templates/campaign/list.html
{% set page_title = "Manage Campaigns" %}
{% extends "layouts/base_admin.html" %}

{% block body %}
<div class="container">
    <h2 class="pull-left">{{ _('Manage Campaigns') }}</h2>
    <div class="pull-right">
        <a class="btn btn-success" href="{{ url_for('campaign.country_type') }}"><strong>{{ _('Add') }} +</strong></a>
    </div>
    <table class="table" id="campaigns-list">
        <thead>
            <tr>
                <th class="col-sm-2">Title</th>
                <th class="col-sm-2">Type</th>
                <th class="col-sm-4">Targets</th>
                <th class="col-sm-1">Calls</th>
                <th class="col-sm-1">Status</th>
                <th class="col-sm-2"></th>
            </tr>
        </thead>
        {% for c in campaigns %}
        <tr>
            <td>{{c.name}}</td>
            <td>{{c.country_code|upper}} {{c.campaign_type_display()}}</td>
            <td><div class="limit-height-50">{{c.targets_display()|safe}}</div></td>
            <td>{{calls[c.id] }}</td>
            <td><span class="glyphicon {% if c.status == 'live' %}glyphicon-play text-success{%elif c.status=='paused'%}glyphicon-pause text-warning{%else%}glyphicon-stop text-danger{%endif%}"></td>
            <td><a href="{{url_for('campaign.form', campaign_id=c.id)}}">edit</a> /
                <a href="{{url_for('campaign.copy', campaign_id=c.id)}}">copy</a> / 
                <a href="{{url_for('campaign.launch', campaign_id=c.id)}}">test</a> /
                <a href="{{url_for('campaign.calls', campaign_id=c.id)}}">log</a>
            </td>
        </tr>
        {%endfor%}
    </table>
</div>
{% endblock %}