call_server/admin/views.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template, current_app, flash, url_for, redirect, request
from flask_login import login_required, current_user
from flask_babel import gettext as _

from ..extensions import db, cache
from sqlalchemy.sql import func, desc

from .models import Blocklist
from .forms import BlocklistForm

from ..campaign.models import TwilioPhoneNumber, Campaign
from ..call.models import Call
from ..campaign.constants import STATUS_PAUSED
from ..api.constants import API_TIMESPANS
from ..utils import get_one_or_create
from ..user.models import User

admin = Blueprint('admin', __name__, url_prefix='/admin')


# all admin routes require login
@admin.before_request
@login_required
def before_request():
    pass


@admin.route('/')
def dashboard():
    campaigns = (Campaign.query
        .filter(Campaign.status_code >= STATUS_PAUSED)
        .order_by(desc(Campaign.status_code), desc(Campaign.id))
    )
    calls_by_campaign = (db.session.query(Campaign.id, func.count(Call.id))
            .filter(Campaign.status_code >= STATUS_PAUSED)
            .filter(Call.status == 'completed')
            .join(Call).group_by(Campaign.id))

    today = datetime.today()
    this_month_start = today.replace(day=1)  # first day of the current month
    last_month = this_month_start - timedelta(days=28) # a day in last month
    next_month = today.replace(day=28) + timedelta(days=4)  # a day in next month (for months with 28,29,30,31)

    this_month_end = next_month - timedelta(days=next_month.day)  # the last day of the current month
    last_month_start = last_month - timedelta(days=(last_month.day-1))
    last_month_end = this_month_start - timedelta(days=this_month_start.day)

    calls_this_month = (db.session.query(func.count(Call.id))
            .filter(Call.status == 'completed')
            .filter(Call.timestamp >= this_month_start)
            .filter(Call.timestamp <= this_month_end)
        ).scalar()

    calls_last_month = (db.session.query(func.count(Call.id))
            .filter(Call.status == 'completed')
            .filter(Call.timestamp >= last_month_start)
            .filter(Call.timestamp <= last_month_end)
        ).scalar()

    calls_by_day = (db.session.query(func.date(Call.timestamp), func.count(Call.id))
            .filter(Call.status == 'completed')
            .filter(Call.timestamp >= this_month_start)
            .filter(Call.timestamp <= this_month_end)
            .group_by(func.date(Call.timestamp))
            .order_by(func.date(Call.timestamp))
        )

    return render_template('admin/dashboard.html',
        campaigns=campaigns,
        calls_by_campaign=dict(calls_by_campaign.all()),
        calls_by_day=calls_by_day.all(),
        calls_this_month=calls_this_month,
        calls_last_month=calls_last_month,
    )


@admin.route('/statistics')
def statistics():
    campaigns = Campaign.query.order_by(desc(Campaign.status_code), desc(Campaign.id)).all()
    today = datetime.today()
    this_month_start = today.replace(day=1)  # first day of the current month

    last_month = this_month_start - timedelta(days=28) # a day in last month
    next_month = today.replace(day=28) + timedelta(days=4)  # a day in next month (for months with 28,29,30,31)

    last_month_start = last_month - timedelta(days=(last_month.day-1))
    this_month_end = next_month - timedelta(days=next_month.day)  # the last day of the current month
    return render_template('admin/statistics.html',
        campaigns=campaigns, timespans=API_TIMESPANS,
        default_start=last_month_start.strftime('%Y/%m/%d'),
        default_end=this_month_end.strftime('%Y/%m/%d'))


@admin.route('/system')
def system():
    twilio_numbers = TwilioPhoneNumber.query.all()
    admin_api_key = current_app.config.get('ADMIN_API_KEY')
    twilio_account = current_app.config.get('TWILIO_CLIENT').auth[0]
    political_data_cache = {'US': cache.get('political_data:us'),
                            'CA': cache.get('political_data:ca')}
    blocked = Blocklist.query.order_by(Blocklist.timestamp.desc()).all()
    if not political_data_cache['US']:
        flash(_("US Political Data not yet loaded. Run > python manager.py loadpoliticaldata") , 'warning')
    return render_template('admin/system.html',
                           message_defaults=current_app.config.CAMPAIGN_MESSAGE_DEFAULTS,
                           twilio_numbers=twilio_numbers,
                           twilio_account=twilio_account,
                           admin_api_key=admin_api_key,
                           political_data_cache=political_data_cache,
                           blocked=blocked)


@admin.route('/system/blocklist/create', methods=['GET', 'POST'])
@admin.route('/system/blocklist/<int:blocklist_id>/edit', methods=['GET', 'POST'])
def blocklist(blocklist_id=None):
    edit = False
    if blocklist_id:
        edit = True

    if edit:
        blocklist = Blocklist.query.filter_by(id=blocklist_id).first_or_404()
    else:
        blocklist = Blocklist()

    form = BlocklistForm()
    
    if form.validate_on_submit():
        form.populate_obj(blocklist)

        db.session.add(blocklist)
        db.session.commit()

        flash('Blocklist updated.', 'success')
        return redirect(url_for('admin.system'))

    return render_template('admin/blocklist.html', blocklist=blocklist, form=form)


# for flask-limit exempt-when
# called with request context
def admin_phone():
    if current_user.is_authenticated():
        return True

    # if calling from embedded website, check list of admin users
    phone = request.values.get('userPhone')
    return User.query.filter_by(phone=phone).count()

@admin.route('/twilio/resync', methods=['POST'])
def twilio_resync():
    """ One-way sync of Twilio numbers from REST Client down to our database
    Adds new numbers, saves voice_application_sid, and removes stale entries."""

    client = current_app.config.get('TWILIO_CLIENT')
    twilio_numbers = client.incoming_phone_numbers.list()

    new_numbers = []
    deleted_numbers = []
    for num in twilio_numbers:
        obj, created = get_one_or_create(db.session, TwilioPhoneNumber,
                                         number=num.phone_number,
                                         twilio_sid=num.sid)
        if created:
            new_numbers.append(num.phone_number)

        # update voice application sid from twilio
        obj.twilio_app = num.voice_application_sid
        db.session.add(obj)
        db.session.commit()

    # find any stale numbers we have in the db that aren't in the response
    stale_numbers = TwilioPhoneNumber.query.filter(
        TwilioPhoneNumber.number.notin_([n.phone_number for n in twilio_numbers]))
    # and remove them
    # TODO, check if delete will cascade to campaign
    for num in stale_numbers.all():
        deleted_numbers.append(str(num.number))
        db.session.delete(num)
    db.session.commit()

    if new_numbers:
        flash(_("Added Twilio Number: ") + ', '.join(new_numbers), 'success')
    if deleted_numbers:
        flash(_("Removed Twilio Number: ") + ', '.join(deleted_numbers), 'warning')
    else:
        flash(_("Twilio Numbers are Up to Date"), 'success')

    return redirect(url_for('admin.system'))

call_server/user/views.py
from uuid import uuid4
from datetime import datetime

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask_mail import Message
from flask_babel import gettext as _
from flask_login import login_required, login_user, current_user, logout_user, confirm_login, login_fresh

from ..extensions import db, mail, login_manager

from .models import User
from .forms import (CreateUserForm, UserForm, UserRoleForm, LoginForm, ReauthForm,
    RecoverPasswordForm, ChangePasswordForm, InviteUserForm, RemoveUserForm)
from .constants import USER_NEW, USER_ACTIVE, USER_ADMIN
from .decorators import admin_required

user = Blueprint('user', __name__)


@user.route('/admin/user')
@login_required
@admin_required
def index():
    users = User.query.all()
    return render_template('user/list.html', users=users)


@user.route('/user/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('admin.dashboard'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                                form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash(_("Logged in"), 'success')
            else:
                flash(_("Unable to log in"), 'warning')

            user.last_accessed = datetime.now()
            db.session.add(user)
            db.session.commit()

            return redirect(form.next.data or url_for('admin.dashboard'))
        else:
            flash(_('Sorry, invalid login'), 'warning')

    return render_template('user/login.html', form=form)


@user.route('/user/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                                form.password.data)
        if user and authenticated:
            confirm_login()
            flash(_('Reauthenticated.'), 'success')
            return redirect(form.next.data or url_for('user.change_password'))

        flash(_('Password is incorrect.'), 'warning')
    return render_template('user/reauth.html', form=form)


@user.route('/user/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('site.index'))


@user.route('/user/create_account', methods=['GET', 'POST'])
def create_account():
    user = None
    if 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        return render_template('user/invalid_invitation.html')

    form = CreateUserForm(obj=user)

    # can't use form.validate_on_submit, because username and email won't be unique
    if form.is_submitted():
        if form.password.validate(form) \
            and form.password_confirm.validate(form) \
                and form.phone.validate(form):

            # don't use populate_obj, which creates a new user, overwrite invidual fields instead
            user.email = form.email.data
            user.name = form.name.data
            user.password = form.password.data
            user.phone = form.phone.data
            user.status_code = USER_ACTIVE
            user.last_accessed = datetime.now()
            user.activation_key = None

            db.session.add(user)
            db.session.commit()

            if login_user(user):
                return redirect(form.next.data or url_for('admin.dashboard'))

    next = url_for('user.create_account', email=user.email, activation_key=user.activation_key)
    return render_template('user/create_account.html', next=next, form=form)


@user.route('/user/change_password', methods=['GET', 'POST'])
# not login_required, user auth'ed by activation_key
def change_password():
    user = None
    if current_user.is_authenticated():
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(email=user.email, activation_key=user.activation_key)

    if form.validate_on_submit():
        user.password = form.password.data
        user.activation_key = None
        db.session.add(user)
        db.session.commit()

        flash(_("Your password has been changed, please log in again"),
              "success")
        return redirect(url_for("user.login"))

    return render_template("user/change_password.html", user=user, form=form)


@user.route('/user/reset_password', methods=['GET', 'POST'])
# not login_required, because user doesn't know password
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash(_('Please check your email for instructions on how to access your account'), 'success')

            user.activation_key = str(uuid4())
            db.session.add(user)
            db.session.commit()

            url = url_for('user.change_password',
                email=user.email,
                activation_key=user.activation_key,
                _external=True)
            body = render_template('user/email/reset_password.txt',
                sitename=current_app.config['SITENAME'],
                username=user.name,
                url=url)
            message = Message(subject='Reset your password for ' + current_app.config['SITENAME'],
                body=body,
                recipients=[user.email])
            mail.send(message)

            return render_template('user/reset_password.html', form=form)
        else:
            flash(_('Sorry, no user found for that email address'), 'error')

    return render_template('user/reset_password.html', form=form)


@user.route('/user/profile', methods=['GET', 'POST'], defaults={'user_id': None})
@user.route('/user/<int:user_id>/profile', methods=['GET', 'POST'])
@login_required
def profile(user_id):
    if user_id:
        user = User.query.get(user_id)
    else:
        user = User.query.filter_by(email=current_user.email).first_or_404()

    form = UserForm(obj=user,
                    next=request.args.get('next'))

    if form.validate_on_submit():
        user.email = form.email.data
        user.name = form.name.data
        user.phone = form.phone.data

        db.session.add(user)
        db.session.commit()

        flash('User profile updated.', 'success')

    return render_template('user/profile.html', user=user, form=form)


@user.route('/user/invite', methods=['GET', 'POST'])
@login_required
@admin_required
def invite():
    form = InviteUserForm()

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)

        user.activation_key = str(uuid4())
        user.status_code = USER_NEW
        user.password = user.activation_key  # reuse key until first login

        db.session.add(user)
        db.session.commit()

        url = url_for('user.create_account',
            email=user.email,
            activation_key=user.activation_key,
            _external=True, _scheme='https')
        body = render_template('user/email/invite_user.txt', sitename=current_app.config['SITENAME'],
            username=user.name,
            url=url)
        message = Message(subject='Create account on ' + current_app.config['SITENAME'],
            body=body,
            recipients=[user.email])
        mail.send(message)

        flash(_('Invited ' + user.email), 'success')
        return redirect(url_for('user.index'))

    return render_template('user/invite.html', form=form)


@user.route('/admin/user/<int:user_id>/role', methods=['GET', 'POST'])
@login_required
@admin_required
def role(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserRoleForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        if ((user == current_user)
        and (user.role_code is USER_ADMIN)
        and (int(form.data['role_code']) > 0)):
            flash("Cannot remove your own admin role.", 'warning')
            return render_template('user/role.html', user=user, form=form)
        else:
            form.populate_obj(user)
            db.session.add(user)
            db.session.commit()

            flash('User role updated.', 'success')
        return redirect(url_for('user.index'))

    return render_template('user/role.html', user=user, form=form)


@user.route('/user/<int:user_id>/remove', methods=['GET', 'POST'])
@login_required
@admin_required
def remove(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()

    if user == current_user:
        flash('Cannot remove yourself.', 'warning')
        return redirect(url_for('user.index'))

    form = RemoveUserForm(obj=user, username=user.name)

    if form.validate_on_submit():
        db.session.delete(user)
        db.session.commit()

        flash('User removed.', 'success')
        return redirect(url_for('user.index'))

    return render_template('user/remove.html', user=user, form=form)


@user.route('/user/lang/', methods=['POST'])
def lang():

call_server/templates/layouts/base.html
<!DOCTYPE html>
<html>
 <head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">

  <title>{%block title%}{{SITENAME|default('Call Power')}} | {{ page_title }}{%endblock%}</title>
  <!-- Chrome Frame for browsers that support it -->
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block extra_meta %}{% endblock %}

  <link rel="shortcut icon" type="image/ico" href="static/images/favicon.png">

  {% assets "vendor_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% assets "site_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {%block styles%}{%endblock%}
 </head>

 <body id="callpower">
  <div id="global_message_container"></div>
  {%block navbar%}
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">{{SITENAME|default('Call Power')}}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
            <li><a href="{{ url_for('admin.dashboard') }}">{{ _('Admin') }}</a></li>
            {% else %}
            <li><a href="{{ url_for('user.login') }}">{{ _('Login') }}</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  {%endblock%}

    {% block flash_message %}
      <div class="container">
          <div id='flash_message_container'>
      {% with messages = get_flashed_messages(with_categories=True) %}
            {% for category, msg in messages %}
              <div class="alert alert-{%if category == 'message'%}info{%else%}{{ category }}{%endif%}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                  {{ msg }}
              </div>
            {% endfor %}
      {% endwith %}
          </div>
      </div>
    {% endblock %}

    <div class="container">
    {%block body%}{%endblock%}
    </div>
    

    <footer class="footer">
    <div class="container">
      <p class="text-muted"><span class="navbar-left">
      <a href="https://www.gnu.org/licenses/agpl.html" target="_blank">&copy; AGPL</a> 2015-{{now.year}}
      </span>
      {% if version %}<span class="navbar-right">v{{version}}</span>{% endif %}
      </p>
    </div>
    </footer>
 </body>
  {%block before_scripts %}{% endblock %}

  {% assets "vendor_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}

  {% assets "site_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}

  {%block scripts %}{% endblock %}
</html>

call_server/templates/layouts/base_admin.html
{% extends "layouts/base.html" %}

{% block navbar %}
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">{{SITENAME|default('Call Power')}} Admin</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        {% if current_user.is_authenticated() %}
        <ul class="nav navbar-nav">
          <li><a href="{{ url_for('admin.dashboard') }} ">Dashboard</a></li>
          <li><a href="{{ url_for('campaign.index') }}">Campaigns</a></li>
          <li><a href="{{ url_for('admin.statistics') }} ">Statistics</a></li>
          {% if current_user.is_admin() %}
          <li><a href="{{ url_for('admin.system') }} ">System</a></li>
          {% endif %}
        </ul>
        {% endif %}
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">User <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              {% if current_user.is_authenticated() %}
                {% if current_user.is_admin() %}
                <li><a href="{{ url_for('user.index') }} ">{{ _('Manage Users') }}</a></li>
                <li class="divider"></li>
                {%endif%}
              <li><a href="{{ url_for('user.profile') }}">{{ _('Profile') }}</a></li>
              <li><a href="{{ url_for('user.change_password') }}">{{ _('Change Password') }}</a></li>
              <li class="divider"></li>
              <li><a href="{{ url_for('user.logout') }}">{{ _('Log out') }}</a></li>
              {% else %}
              <li><a href="{{ url_for('user.login') }}">{{ _('Log in') }}</a></li>
              {% endif %}
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
{% endblock %}

{% block before_scripts %}
<meta name="csrf-token" content="{{ csrf_token() }}">
<script>
    window.CallPower = {
      Config: {
        OPENSTATES_URL: "https://openstates.org/api/v1/legislators/",
        OPENSTATES_API_KEY: "{{OPENSTATES_API_KEY}}",
        OPENNORTH_URL: "https://represent.opennorth.ca/",
        {% if twilio_capability %}TWILIO_CAPABILITY: "{{twilio_capability.to_jwt()|safe}}", {%endif%}
      }
    };
</script>
{% endblock %}